export const mockProcesos = [
  {
    id: "1",
    radicado: "11001310300120230012300",
    partes: { demandante: "Banco de Bogotá S.A.", demandado: "Constructora Arco Ltda." },
    despacho: "Juzgado 12 Civil del Circuito de Bogotá",
    jurisdiccion: "Civil Ordinaria",
    estado: "activo",
    ultimaActuacion: "Auto admisorio de demanda",
    fechaUltimaActuacion: "2024-03-15",
    alertas: 2,
  },
  {
    id: "2",
    radicado: "05001310300220230045800",
    partes: { demandante: "Seguros Bolívar S.A.", demandado: "Transportes del Norte S.A.S." },
    despacho: "Juzgado 3 Civil del Circuito de Medellín",
    jurisdiccion: "Civil Ordinaria",
    estado: "en_despacho",
    ultimaActuacion: "Traslado para alegatos de conclusión",
    fechaUltimaActuacion: "2024-03-18",
    alertas: 1,
  },
  {
    id: "3",
    radicado: "76001310300320230098700",
    partes: { demandante: "Inversiones Palermo S.A.S.", demandado: "Constructora Pacífico Ltda." },
    despacho: "Juzgado 7 Civil del Circuito de Cali",
    jurisdiccion: "Civil Ordinaria",
    estado: "urgente",
    ultimaActuacion: "Auto que fija fecha de audiencia",
    fechaUltimaActuacion: "2024-03-19",
    alertas: 3,
  },
  {
    id: "4",
    radicado: "08001310300120230023400",
    partes: { demandante: "Petrocolombia S.A.", demandado: "Servicios Offshore Ltda." },
    despacho: "Juzgado 2 Civil del Circuito de Barranquilla",
    jurisdiccion: "Civil Ordinaria",
    estado: "activo",
    ultimaActuacion: "Contestación de la demanda",
    fechaUltimaActuacion: "2024-02-28",
    alertas: 0,
  },
  {
    id: "5",
    radicado: "11001310300520220067800",
    partes: { demandante: "Fiduciaria Bogotá S.A.", demandado: "Inmobiliaria Central Ltda." },
    despacho: "Juzgado 18 Civil del Circuito de Bogotá",
    jurisdiccion: "Civil Ordinaria",
    estado: "suspendido",
    ultimaActuacion: "Auto que suspende el proceso",
    fechaUltimaActuacion: "2024-01-10",
    alertas: 0,
  },
]

export const mockActuaciones = [
  {
    id: "a1",
    procesoId: "1",
    fecha: "2023-08-15",
    tipo: "Demanda",
    descripcion: "Presentación de demanda ordinaria por incumplimiento contractual",
    documentoId: "d1",
    estado: "completado",
  },
  {
    id: "a2",
    procesoId: "1",
    fecha: "2023-09-02",
    tipo: "Auto admisorio",
    descripcion: "Se admite la demanda y se ordena notificar al demandado",
    documentoId: "d2",
    estado: "completado",
  },
  {
    id: "a3",
    procesoId: "1",
    fecha: "2023-11-14",
    tipo: "Contestación",
    descripcion: "Contestación de demanda con excepciones de mérito",
    documentoId: "d3",
    estado: "completado",
  },
  {
    id: "a4",
    procesoId: "1",
    fecha: "2024-01-20",
    tipo: "Audiencia inicial",
    descripcion: "Audiencia de conciliación, saneamiento y fijación del litigio",
    documentoId: "d4",
    estado: "completado",
  },
  {
    id: "a5",
    procesoId: "1",
    fecha: "2024-03-15",
    tipo: "Decreto de pruebas",
    descripcion: "Auto que decreta las pruebas solicitadas por las partes",
    documentoId: "d5",
    estado: "actual",
  },
  {
    id: "a6",
    procesoId: "1",
    fecha: "2024-05-10",
    tipo: "Audiencia de pruebas",
    descripcion: "Práctica de pruebas decretadas",
    documentoId: null,
    estado: "pendiente",
  },
  {
    id: "a7",
    procesoId: "1",
    fecha: "2024-07-15",
    tipo: "Sentencia",
    descripcion: "Sentencia de primera instancia",
    documentoId: null,
    estado: "pendiente",
  },
]

export const mockDocumento = {
  id: "d5",
  actuacionId: "a5",
  tipo: "Auto interlocutorio",
  fecha: "2024-03-15",
  juez: "Dr. Carlos Andrés Rodríguez Gómez",
  partes: ["Banco de Bogotá S.A.", "Constructora Arco Ltda."],
  resumenIA: {
    tipodocumento: "Auto interlocutorio de decreto de pruebas",
    decision: "El juzgado decreta las pruebas documentales y testimoniales solicitadas por ambas partes. Se admiten 3 testimonios del demandante y 2 del demandado. Se inadmite el dictamen pericial de parte por extemporáneo.",
    fechasImportantes: [
      { fecha: "2024-05-10", descripcion: "Audiencia de práctica de pruebas" },
      { fecha: "2024-04-05", descripcion: "Plazo para notificar testigos" },
    ],
    riesgos: [
      "El dictamen pericial inadmitido puede debilitar la posición del demandante en cuanto a cuantificación de perjuicios",
      "Los testimonios aceptados favorecen principalmente al demandado",
    ],
    proximosPasos: [
      "Notificar a los testigos dentro de los 20 días siguientes",
      "Preparar interrogatorio para audiencia del 10 de mayo",
      "Evaluar solicitud de nuevo dictamen pericial dentro del término legal",
    ],
  },
}

export const mockAlertas = [
  {
    id: "al1",
    tipo: "urgente",
    titulo: "Audiencia en 5 días",
    descripcion: "Audiencia de práctica de pruebas programada para el 10 de mayo de 2024",
    proceso: "11001310300120230012300",
    procesoId: "1",
    timestamp: "2024-05-05T09:00:00",
    leida: false,
  },
  {
    id: "al2",
    tipo: "info",
    titulo: "Nuevo auto publicado",
    descripcion: "Se publicó auto interlocutorio en el proceso de Seguros Bolívar vs. Transportes del Norte",
    proceso: "05001310300220230045800",
    procesoId: "2",
    timestamp: "2024-03-18T14:32:00",
    leida: false,
  },
  {
    id: "al3",
    tipo: "advertencia",
    titulo: "Proceso pasó a despacho",
    descripcion: "El proceso 05001... está ahora en despacho del juez para fallo",
    proceso: "05001310300220230045800",
    procesoId: "2",
    timestamp: "2024-03-18T10:15:00",
    leida: true,
  },
  {
    id: "al4",
    tipo: "urgente",
    titulo: "Posible vencimiento de término",
    descripcion: "El plazo para recurrir el auto del 15 de marzo vence en 3 días hábiles",
    proceso: "76001310300320230098700",
    procesoId: "3",
    timestamp: "2024-03-19T08:00:00",
    leida: false,
  },
  {
    id: "al5",
    tipo: "info",
    titulo: "Actuación registrada",
    descripcion: "Nueva actuación registrada: contestación de demanda en proceso Petrocolombia",
    proceso: "08001310300120230023400",
    procesoId: "4",
    timestamp: "2024-02-28T16:45:00",
    leida: true,
  },
  {
    id: "al6",
    tipo: "urgente",
    titulo: "Audiencia programada con poco tiempo",
    descripcion: "Audiencia de conciliación fijada para el 25 de marzo. Faltan 6 días",
    proceso: "76001310300320230098700",
    procesoId: "3",
    timestamp: "2024-03-19T09:30:00",
    leida: false,
  },
]
